[project]
name = "autoscout24"
description = "A python library to scrape data from https://autoscout24.com"

version = "0.0.2"
readme = "README.md"
requires-python = ">=3.7"
authors = [
    { name="Roy Savion", email="roysav123@gmail.com" },
]

